import { useEffect, useMemo, useState } from 'react'
import { Search, RefreshCw, Users, CheckCircle2, Clock3, UserCheck, Filter, X, LogOut, ChevronRight } from 'lucide-react'
import { getApplicants, updateApplicantStatus } from '../services/dashboardService'

const STATUSES=['Semua','Baru','Seleksi Administrasi','Lolos','Tidak Lolos','Wawancara','Diterima']
const statusClass=s=>({Baru:'bg-blue-400/10 text-blue-300 border-blue-400/20','Seleksi Administrasi':'bg-amber-400/10 text-amber-300 border-amber-400/20',Lolos:'bg-emerald-400/10 text-emerald-300 border-emerald-400/20','Tidak Lolos':'bg-rose-400/10 text-rose-300 border-rose-400/20',Wawancara:'bg-violet-400/10 text-violet-300 border-violet-400/20',Diterima:'bg-green-400/10 text-green-300 border-green-400/20'}[s]||'bg-white/5 text-slate-300 border-white/10')
export default function DashboardPage({onLogout}){
 const [data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[division,setDivision]=useState('Semua'),[status,setStatus]=useState('Semua'),[selected,setSelected]=useState(null),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);setError('');try{const r=await getApplicants();setData(r.records||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const divisions=useMemo(()=>['Semua',...new Set(data.flatMap(x=>[x.divisionFirstChoice,x.divisionSecondChoice]).filter(Boolean))],[data])
 const filtered=useMemo(()=>data.filter(x=>{const hay=[x.registrationNumber,x.name,x.nim,x.email,x.className,x.major].join(' ').toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(division==='Semua'||x.divisionFirstChoice===division||x.divisionSecondChoice===division)&&(status==='Semua'||x.status===status)}),[data,q,division,status])
 const stats={total:data.length,new:data.filter(x=>x.status==='Baru').length,passed:data.filter(x=>x.status==='Lolos').length,accepted:data.filter(x=>x.status==='Diterima').length}
 const save=async(nextStatus,note='')=>{if(!selected)return;setSaving(true);try{const r=await updateApplicantStatus(selected.registrationNumber,nextStatus,note);setData(d=>d.map(x=>x.registrationNumber===r.registrationNumber?r:x));setSelected(r)}catch(e){alert(e.message)}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#031521] px-4 pb-12 pt-24 text-white md:px-8"><div className="mx-auto max-w-7xl">
  <header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-400">PANITIA • OPREC 2026/2027</span><h1 className="mt-2 font-display text-3xl font-extrabold">Dashboard Pendaftar</h1><p className="mt-2 text-sm text-slate-400">Kelola dan pantau seluruh pendaftaran GANAS Nusa Putra.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-bold hover:bg-white/10"><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-400 hover:text-white"><LogOut size={16}/> Keluar</button></div></header>
  {error&&<div className="mb-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Users,'Total Pendaftar',stats.total],[Clock3,'Status Baru',stats.new],[CheckCircle2,'Lolos',stats.passed],[UserCheck,'Diterima',stats.accepted]].map(([Icon,label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-[#0c1d29]/80 p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-400">{label}</span><Icon size={18} className="text-blue-400"/></div><div className="mt-3 font-display text-3xl font-extrabold">{value}</div></div>)}</div>
  <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[#0c1d29]/80"><div className="border-b border-white/10 p-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3.5 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, NIM, email, nomor pendaftaran..." className="w-full rounded-xl border border-white/10 bg-[#061725] py-3 pl-10 pr-4 text-sm outline-none focus:border-blue-500"/></label><div className="flex gap-2"><select value={division} onChange={e=>setDivision(e.target.value)} className="rounded-xl border border-white/10 bg-[#061725] px-3 text-sm outline-none"><option value="Semua">Semua Divisi</option>{divisions.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#061725] px-3 text-sm outline-none">{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="flex items-center gap-2 px-4 pb-3 text-xs text-slate-500"><Filter size={14}/> Menampilkan {filtered.length} dari {data.length} pendaftar</div></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/[.025] text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Pendaftar</th><th className="px-5 py-4">NIM / Kelas</th><th className="px-5 py-4">Jurusan</th><th className="px-5 py-4">Pilihan Divisi</th><th className="px-5 py-4">Status</th><th></th></tr></thead><tbody className="divide-y divide-white/5">{loading?<tr><td colSpan="6" className="px-5 py-12 text-center text-slate-500">Memuat data...</td></tr>:filtered.length===0?<tr><td colSpan="6" className="px-5 py-12 text-center text-slate-500">Tidak ada pendaftar yang cocok.</td></tr>:filtered.map(x=><tr key={x.registrationNumber} onClick={()=>setSelected(x)} className="cursor-pointer transition hover:bg-white/[.025]"><td className="px-5 py-4"><div className="font-bold">{x.name}</div><div className="mt-1 text-xs text-slate-500">{x.registrationNumber}</div></td><td className="px-5 py-4"><div>{x.nim}</div><div className="mt-1 text-xs text-slate-500">{x.className}</div></td><td className="px-5 py-4 text-slate-300">{x.major}</td><td className="px-5 py-4"><div className="text-xs text-blue-300">1. {x.divisionFirstChoice}</div><div className="mt-1 text-xs text-slate-500">2. {x.divisionSecondChoice}</div></td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold ${statusClass(x.status)}`}>{x.status||'Baru'}</span></td><td className="px-5"><ChevronRight size={17} className="text-slate-600"/></td></tr>)}</tbody></table></div></section>
 </div>{selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm md:items-center md:p-6" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl border border-white/10 bg-[#081b29] p-6 shadow-2xl md:rounded-3xl"><div className="mb-6 flex items-start justify-between"><div><span className="text-[10px] font-bold uppercase tracking-wider text-blue-400">{selected.registrationNumber}</span><h2 className="mt-1 font-display text-2xl font-extrabold">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">{selected.email}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-white"><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{[['NIM',selected.nim],['Kelas',selected.className],['Jurusan',selected.major],['Pilihan 1',selected.divisionFirstChoice],['Pilihan 2',selected.divisionSecondChoice],['Waktu Daftar',selected.timestamp]].map(([a,b])=><div key={a} className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{a}</div><div className="mt-1 text-sm font-semibold">{b||'-'}</div></div>)}</div><div className="mt-4 space-y-4"><Detail title="Motivasi" value={selected.motivation}/><Detail title="Pengalaman Organisasi" value={selected.organizationExperience}/></div><div className="mt-6 border-t border-white/10 pt-5"><label className="text-xs font-bold text-slate-400">Ubah Status Seleksi</label><div className="mt-2 flex flex-wrap gap-2">{STATUSES.slice(1).map(s=><button disabled={saving} key={s} onClick={()=>save(s,selected.note||'')} className={`rounded-lg border px-3 py-2 text-xs font-bold ${selected.status===s?'border-blue-500 bg-blue-500/10 text-blue-300':'border-white/10 text-slate-400 hover:text-white'}`}>{s}</button>)}</div></div></div></div>}</main>
}
function Detail({title,value}){return <div className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{title}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{value||'Tidak diisi.'}</p></div>}
